name: Push Workflow
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
    - '**.md'
    - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Output
        run: echo "Готово"
